### ISSUE TITLE
Player can't shoot fireball when its back is against a wall.

### ISSUE THREAD

**Issue by https123456789** [LGgameLAB/The-Caverns#8]
@LGgameLAB I was hoping you might be able to fix this at some point (probably after I finish adding the inventory system to avoid git conflicts) see as you made the player.

**Comment by LGgameLAB** [comment]
On it!

**Comment by https123456789** [comment]
Resolved in commit [24382a3f46dd5b9fb706c3d3eb9d86343d7557fa](https://github.com/LGgameLAB/The-Caverns/commit/24382a3f46dd5b9fb706c3d3eb9d86343d7557fa).
